#define Liga_D0() PORTD |= (1<<4) 
#define Liga_D1() PORTD |= (1<<6) 
#define Liga_D2() PORTD |= (1<<7) 
#define Liga_D3() PORTB |= (1<<4) 
#define Liga_D4() PORTB |= (1<<5) 
#define Liga_D5() PORTB |= (1<<6) 
#define Liga_D6() PORTC |= (1<<6) 
#define Liga_D7() PORTC |= (1<<7) 

#define Desliga_D0() PORTD &= ~(1<<4)
#define Desliga_D1() PORTD &= ~(1<<6)
#define Desliga_D2() PORTD &= ~(1<<7)
#define Desliga_D3() PORTB &= ~(1<<4)
#define Desliga_D4() PORTB &= ~(1<<5)
#define Desliga_D5() PORTB &= ~(1<<6)
#define Desliga_D6() PORTC &= ~(1<<6)
#define Desliga_D7() PORTC &= ~(1<<7)

#define DLED1() PORTB &= ~(1<<7)
#define DLED2() PORTB &= ~(1<<3)
#define DLED3() PORTB &= ~(1<<1)
#define DLED4() PORTB &= ~(1<<2) 
#define DLED5() PORTD &= ~(1<<4)
#define DLED6() PORTD &= ~(1<<6)
#define DLED7() PORTD &= ~(1<<7)
#define DLED8() PORTB &= ~(1<<4)
#define DLED9() PORTB &= ~(1<<5)
#define DLED10() PORTB &= ~(1<<6)
#define DLED11() PORTC &= ~(1<<6)
#define DLED12() PORTC &= ~(1<<7)


#define LLED1() PORTB |= (1<<7) 
#define LLED2() PORTB |= (1<<3)
#define LLED3() PORTB |= (1<<1) 
#define LLED4() PORTB |= (1<<2) 
#define LLED5() PORTD |= (1<<4) 
#define LLED6() PORTD |= (1<<6) 
#define LLED7() PORTD |= (1<<7) 
#define LLED8() PORTB |= (1<<4) 
#define LLED9() PORTB |= (1<<5) 
#define LLED10() PORTB |= (1<<6) 
#define LLED11() PORTC |= (1<<6) 
#define LLED12() PORTC |= (1<<7) 

#define TLED1() PORTB ^= (1<<7)
#define TLED2() PORTB ^= (1<<3)
#define TLED3() PORTB ^= (1<<1)
#define TLED4() PORTB ^= (1<<2)
#define TLED5() PORTD ^= (1<<4)
#define TLED6() PORTD ^= (1<<6)
#define TLED7() PORTD ^= (1<<7)
#define TLED8() PORTB ^= (1<<4)
#define TLED9() PORTB ^= (1<<5)
#define TLED10() PORTB ^= (1<<6)
#define TLED11() PORTC ^= (1<<6)
#define TLED12() PORTC ^= (1<<7)


#define Toggle_D0() PORTD ^= (1<<4)
#define Toggle_D1() PORTD ^= (1<<6)
#define Toggle_D2() PORTD ^= (1<<7)
#define Toggle_D3() PORTB ^= (1<<4)
#define Toggle_D4() PORTB ^= (1<<5)
#define Toggle_D5() PORTB ^= (1<<6)
#define Toggle_D6() PORTC ^= (1<<6)
#define Toggle_D7() PORTC ^= (1<<7)

#define Liga_Strobe() PORTB |= (1<<7) 
#define Liga_Feed() PORTB |= (1<<3)
#define Liga_Sel_in() PORTB |= (1<<1) 
#define Liga_Init() PORTB |= (1<<2) 

#define Desliga_Strobe() PORTB &= ~(1<<7)
#define Desliga_Feed() PORTB &= ~(1<<3)
#define Desliga_Sel_in() PORTB &= ~(1<<1)
#define Desliga_Init() PORTB &= ~(1<<2) 

#define Toggle_Strobe() PORTB |= (1<<7)
#define Toggle_Feed() PORTB |= (1<<3)
#define Toggle_Sel_in() PORTB |= (1<<1)
#define Toggle_Init() PORTB |= (1<<2)


#define Ch_error_lig !(PIND & (1<<0)) 
#define Ch_ack_lig !(PIND & (1<<1)) 
#define Ch_busy_lig !(PIND & (1<<5)) 
#define Ch_prog_lig !(PINE & (1<<2)) 
#define Ch_paper_out_lig !(PINF & (1<<7)) 
#define Ch_sel_out_lig !(PINF & (1<<6)) 

#define Ch_error_des (PIND & (1<<0))
#define Ch_ack_des (PIND & (1<<1))
#define Ch_busy_des (PIND & (1<<5))
#define Ch_prog_des (PINE & (1<<2))
#define Ch_paper_out_des (PINF & (1<<7))
#define Ch_sel_out_des (PINF & (1<<6))
